### ISSUE TITLE
安装红外感应灯须知

### ISSUE THREAD

**Issue by ahwuhui123** [w3ctrain/w3ctrain.github.io#4]
1、红外线人体感应灯安装时请把智能灯具安装在人经常活动的地方(天花板或墙壁上)，可提高其灵敏度及工作范围。
2、不要安装在潮湿的天花板或墙壁上。
3、清洗时要先断开电源。
4、清洗时请选取无腐蚀性的清洁剂。
5、灯具安装后在一定空间不能用酸性或碱性的化学溶剂，否则对灯具的电镀或喷漆造成损坏。
关于红外感应灯功能特点灯一系列问题可以参考[url="http://www.cr-leds.com/Article/rthwxgydzs.html"](http://www.cr-leds.com/Article/rthwxgydzs.html)[/url]

**Comment by MissCuriosity** [comment]
= =这是个测试or推广issue吗？
